# Codecov configuration for combined Rust + Python coverage
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: auto
        threshold: 5%
    patch:
      default:
        target: 80%

# Flag configuration for separate language tracking
flags:
  python:
    paths:
      - python/
    carryforward: true
  rust:
    paths:
      - crates/
    carryforward: true

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: false
